apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-ui
  labels:
    app: task-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-ui
  template:
    metadata:
      labels:
        app: task-ui
    spec:
      containers:
        - name: task-ui
          image: askpocregistry.azurecr.io/todoui:2
          ports:
            - containerPort: 80  # Change to 3001 if your container uses `serve`
---
apiVersion: v1
kind: Service
metadata:
  name: task-ui-service
spec:
  selector:
    app: task-ui
  ports:
    - protocol: TCP
      port: 80       # External service port
      targetPort: 3001 # Container port
  type: LoadBalancer  # Use NodePort for local clusters like Minikube
